/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/supply': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get current vehicle positions
     * @description Returns a list of all available scooters and carpool drivers on the map. Frontend should poll this.
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description Successful retrieval */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            /**
             * @example {
             *       "timestamp": "2023-10-27T10:30:00Z",
             *       "vehicles": [
             *         {
             *           "id": "s_01",
             *           "type": "SCOOTER",
             *           "lat": 55.7523,
             *           "lon": 48.7445,
             *           "battery_level": 88
             *         },
             *         {
             *           "id": "c_05",
             *           "type": "CARPOOL_DRIVER",
             *           "lat": 55.755,
             *           "lon": 48.75,
             *           "status": "MOVING"
             *         }
             *       ]
             *     }
             */
            'application/json': unknown
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/route/calculate': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Calculate Optimal Multimodal Route
     * @description Accepts Origin/Dest and User Weights. Runs the optimization algorithm.
     */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': unknown
        }
      }
      responses: {
        /** @description Optimal path found */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            'application/json': unknown
          }
        }
        /** @description No feasible route found (Constraints too tight) */
        404: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
        /** @description Validation Error (e.g., weights don't sum to roughly 1.0) */
        422: {
          headers: {
            [name: string]: unknown
          }
          content?: never
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  '/api/v1/simulation/scenario': {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Set Urban Scenario
     * @description Updates the global physics/cost parameters of the backend (e.g., makes it rain).
     */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          'application/json': {
            scenario: unknown
          }
        }
      }
      responses: {
        /** @description Scenario updated successfully */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            /**
             * @example {
             *       "message": "Scenario changed to RAINY_WEATHER. Scooter speeds reduced to 10km/h."
             *     }
             */
            'application/json': unknown
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    GeoPoint: {
      /**
       * Format: double
       * @example 55.7539
       */
      lat: number
      /**
       * Format: double
       * @example 48.7432
       */
      lon: number
    }
    /** @enum {string} */
    VehicleType: 'SCOOTER' | 'CARPOOL_DRIVER'
    /** @enum {string} */
    TransportMode: 'WALK' | 'SCOOTER' | 'CARPOOL'
    /** @enum {string} */
    ScenarioType: 'NORMAL' | 'MORNING_PEAK' | 'RAINY_WEATHER' | 'MAJOR_ACCIDENT'
    Vehicle: {
      id: string
      type: unknown
      /** Format: double */
      lat: number
      /** Format: double */
      lon: number
      battery_level?: number
      /** @example AVAILABLE */
      status?: string
    }
    VehicleList: {
      /** Format: date-time */
      timestamp?: string
      vehicles?: unknown[]
    }
    /** @description User preferences for the objective function (Lambda values). Should technically sum to 1.0, but backend can normalize. */
    UserWeights: {
      /**
       * Format: float
       * @example 0.5
       */
      w_time?: number
      /**
       * Format: float
       * @example 0.3
       */
      w_cost?: number
      /**
       * Format: float
       * @example 0.2
       */
      w_emissions?: number
      /**
       * Format: float
       * @example 0
       */
      w_comfort?: number
    }
    RouteRequest: {
      origin: unknown
      destination: unknown
      weights: unknown
    }
    RouteMetrics: {
      /** @example 12.5 */
      total_time_min?: number
      /** @example 145 */
      total_price_rub?: number
      /** @example 350.5 */
      total_emissions_g?: number
      /**
       * @description 1-10 scale
       * @example 8.2
       */
      satisfaction_score?: number
    }
    /** @description A specific leg of the trip (e.g., coordinates for one specific street). */
    RouteSegment: {
      mode?: unknown
      distance_km?: number
      duration_min?: number
      /** @example Walk to Technopark Station */
      instruction?: string
      /**
       * @description List of [lat, lon] points for drawing the line on the map.
       * @example [
       *       [
       *         55.75,
       *         48.74
       *       ],
       *       [
       *         55.751,
       *         48.741
       *       ]
       *     ]
       */
      geometry?: number[][]
    }
    RouteResponse: {
      /** @enum {string} */
      status?: 'OPTIMAL' | 'INFEASIBLE' | 'ERROR'
      metrics?: unknown
      segments?: unknown[]
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export type operations = Record<string, never>
